### ISSUE TITLE
Need to use "typescript": "^2.6.2"

### ISSUE THREAD

**Issue by charlesdeng** [samcodex/ngarch#1]
package.json -> "typescript": "^2.6.2"

npm install typescript@'>=2.4.2 <2.7.0'

When build with "typescript = 2.6.2", have error:

ERROR in src/app/core/diagram-elements/diagram-element-drawer.ts(14,7): error TS2322: Type '{ [DiagramElementType.Module]: string[]; [DiagramElementType.Component]: string[]; [DiagramElemen...' is not assignable to type '{ Module: [string, string]; Component: [string, string]; Service: [string, string]; Model: [strin...'.
  Types of property 'Module' are incompatible.
    Type 'string[]' is not assignable to type '[string, string]'.
      Property '0' is missing in type 'string[]'.

**Comment by samcodex** [comment]
Remove the type annotation will fix this issue.
